export const initialMockData = [
  {
    id: '1',
    title: '校园迎新短视频策划与剪辑',
    type: '短视频作品',
    source: '课程作业',
    date: '2023-09',
    role: '导演、剪辑',
    tools: 'Premiere, 剪映',
    background: '新生入学，需要一个有创意、能展现校园风貌的迎新视频。',
    targetUser: '大一新生及家长',
    idea: '采用第一人称跑酷视角，结合校园标志性建筑的转场，展现青春活力。',
    process: '完成了从分镜头脚本撰写、联系演员、三天实地拍摄，到后期剪辑调色。',
    highlights: '发布在校园公众号后，阅读量突破2万，转发超1000次。',
    materials: '分镜脚本.pdf',
    dataFeedback: '播放量 2w+，点赞 1.5k',
    coverName: '迎新视频封面.jpg',
    tags: ['内容策划', '视频策划', '剪辑执行', '网感'],
    jobs: ['短视频策划', '新媒体运营'],
    matchReasons: '作品展现了完整的短视频制作链路，与短视频策划岗位高度契合。',
    projectDescription: '该项目是在新生入学背景下发起，主要面向大一新生及家长。核心目的是展现校园风貌，传达青春活力。在本项目中，我担任导演和剪辑的角色。在执行过程中，我主要负责了分镜头脚本撰写到后期剪辑的全部流程。最终项目在校园内取得了非常好的传播效果。这个过程充分证明了我具备视频策划和剪辑执行等专业能力。',
    interviewScript: '面试官您好，我来介绍一下我的这个“校园迎新短视频”作品。当时因为新生入学，我们决定开展这个项目。目的是为了给新生提供有价值的校园介绍。在这个项目中我主要负责导演和剪辑。具体来说，我完成了从分镜头策划到后期成片的制作。最终，我们的视频播放量突破了两万，收到了非常好的数据反馈。通过这个作品，很好地锻炼了我的视频策划和剪辑能力。',
    optimized: true,
    addedToPortfolio: false,
    createdAt: Date.now() - 100000
  },
  {
    id: '2',
    title: '公众号推文《大学生就业压力观察》',
    type: '图文作品',
    source: '个人自媒体',
    date: '2023-11',
    role: '撰稿人',
    tools: '秀米, 微信公众平台',
    background: '秋招季大学生普遍面临较大心理压力。',
    targetUser: '在校大学生、应届毕业生',
    idea: '通过真实采访3位不同专业背景的学生，以故事化叙事展现普遍困境与出路。',
    process: '收集了问卷数据，进行了3次深度访谈，撰写了3000字的推文并完成排版。',
    highlights: '文章引起共鸣，被多个校园媒体转载。',
    materials: '访谈录音整理稿.docx',
    dataFeedback: '阅读 5k+, 留言 30+',
    coverName: '就业压力推文封面.png',
    tags: ['选题策划', '内容写作', '文字功底', '热点追踪'],
    jobs: ['新媒体运营', '内容运营', '文案策划'],
    matchReasons: '展现了深刻的用户洞察与优秀的文字表达能力，适合内容运营岗位。',
    projectDescription: '',
    interviewScript: '',
    optimized: false,
    addedToPortfolio: true,
    createdAt: Date.now() - 200000
  },
  {
    id: '3',
    title: '某品牌校园营销策划案',
    type: '策划案',
    source: '竞赛比赛',
    date: '2024-03',
    role: '队长、策划核心',
    tools: 'PPT, MindNode',
    background: '大广赛品牌命题，需要提升某快消品牌在校园群体中的知名度。',
    targetUser: '18-22岁大学生',
    idea: '提出“不定义的青春”主题，结合线上盲盒打卡与线下快闪店体验。',
    process: '进行了百人校园问卷调研，完成竞品分析，撰写了30页的整合营销方案。',
    highlights: '获得省级二等奖，方案部分创意被品牌方采纳。',
    materials: '调研数据汇总.xlsx',
    dataFeedback: '省级二等奖',
    coverName: '营销策划案.pdf',
    tags: ['用户洞察', '活动策划', '方案撰写', '策略思维'],
    jobs: ['广告策划', '品牌策划', '活动策划'],
    matchReasons: '具备扎实的市场调研和营销策划能力，适配品牌与活动策划。',
    projectDescription: '',
    interviewScript: '',
    optimized: false,
    addedToPortfolio: true,
    createdAt: Date.now() - 300000
  },
  {
    id: '4',
    title: '校园活动海报视觉设计',
    type: '视觉设计作品',
    source: '社团工作',
    date: '2023-12',
    role: '主设计师',
    tools: 'Photoshop, Illustrator',
    background: '十佳歌手比赛决赛，需要一套具有视觉冲击力的宣发物料。',
    targetUser: '全校师生',
    idea: '采用赛博朋克风格，霓虹灯配色，突出年轻人的张扬个性。',
    process: '确立视觉规范，设计了主海报、门票、工作证、朋友圈倒计时长图。',
    highlights: '设计风格备受好评，活动现场吸引了超千人参与。',
    materials: '设计源文件.psd',
    dataFeedback: '活动参与人数 1000+',
    coverName: '十佳歌手海报.png',
    tags: ['视觉表达', '版式设计', '审美能力'],
    jobs: ['视觉策划', '广告创意'],
    matchReasons: '体现了优秀的审美和使用设计工具进行创意转化的能力。',
    projectDescription: '',
    interviewScript: '',
    optimized: false,
    addedToPortfolio: false,
    createdAt: Date.now() - 400000
  },
  {
    id: '5',
    title: '用户调研与竞品分析报告',
    type: '调研报告',
    source: '课程作业',
    date: '2024-04',
    role: '调研组长',
    tools: 'Excel, SPSS',
    background: '新媒体产品分析课程期末大作业。',
    targetUser: '产品经理、运营人员',
    idea: '对比小红书与得物在年轻用户内容种草路径上的异同。',
    process: '抓取了部分公开数据，构建了评价指标体系，输出了20页的分析报告。',
    highlights: '数据支撑详实，结论部分具有较强的实操指导意义。',
    materials: '问卷原始数据.csv',
    dataFeedback: '课程成绩 95分',
    coverName: '竞品分析报告.pdf',
    tags: ['用户研究', '竞品分析', '数据分析'],
    jobs: ['用户研究助理', '内容运营'],
    matchReasons: '展示了优秀的数据处理能力与产品分析思维。',
    projectDescription: '',
    interviewScript: '',
    optimized: false,
    addedToPortfolio: false,
    createdAt: Date.now() - 500000
  }
];
